CC=g++
FLAGS=-std=c++17 -Wall -g
SOURCEDIR := practice
BUILDDIR := bin

SOURCES = $(wildcard $(SOURCEDIR)/*.c)


all:
	@echo "There is no \"make all\" for this project."
	@echo "You can use \"make help\" to see the list of commands available\n\n"

help:
	@echo "To run a file, just type \"make [filename]\"
	@echo "E.g. type \"make array1\"

