CC=g++
FLAGS=-std=c++17 -Wall -g

all: address_array100 array100 print_100 print_1to100 print_henlo print_henlo2 print_palindrome

address_array100:
	$(CC) $(FLAGS) -o address_array100.out address_array100.cpp

array100:
	$(CC) $(FLAGS) -o array100.out array100.cpp

print_100:
	$(CC) $(FLAGS) -o print_100.out print_100.cpp

print_1to100:
	$(CC) $(FLAGS) -o print_1to100.out print_1to100.cpp

print_henlo:
	$(CC) $(FLAGS) -o print_henlo.out print_henlo.cpp

print_henlo2:
	$(CC) $(FLAGS) -o print_henlo2.out print_henlo2.cpp

print_palindrome:
	$(CC) $(FLAGS) -o print_palindrome.out print_palindrome.cpp

clean: 
	rm *.out *.o
