CC=g++
FLAGS=-std=c++17 -Wall -g

all: factor intro_vector prime2 prime primitives stringtovector

factor:
	$(CC) $(FLAGS) -o factor.out factor.cpp

intro_vector:
	$(CC) $(FLAGS) -o intro_vector.out intro_vector.cpp

prime2:
	$(CC) $(FLAGS) -o prime2.out prime2.cpp

prime:
	$(CC) $(FLAGS) -o prime.out prime.cpp

primitives:
	$(CC) $(FLAGS) -o primitives.out primitives.cpp

stringtovector:
	$(CC) $(FLAGS) -o stringtovector.out stringtovector.cpp

clean: 
	rm *.out *.o
