CC=g++

all: factor intro_vector prime2 prime primitives stringtovector

factor:
	$(CC) -o factor.out factor.cpp

intro_vector:
	$(CC) -o intro_vector.out intro_vector.cpp

prime2:
	$(CC) -o prime2.out prime2.cpp

prime:
	$(CC) -o prime.out prime.cpp

primitives:
	$(CC) -o primitives.out primitives.cpp

stringtovector:
	$(CC) -o stringtovector.out stringtovector.cpp

clean: 
	rm *.out *.o
